name: Generate SSL Certificate

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  obtain-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create build folder
      run: |
        sudo mkdir -p ${{ github.workspace }}/build

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: miigotu/certbot-dns-godaddy:latest
          options: -v ${{ github.workspace }}/build:/build
          run: |
              echo "dns_godaddy_key = ${{ secrets.DNS_GODADDY_KEY }}" >> c.ini
              echo >> c.ini
              echo "dns_godaddy_secret = ${{ secrets.DNS_GODADDY_SECRET }}" >> c.ini
              chmod 600 c.ini
              cat c.ini
              certbot certonly \
                  --authenticator dns-godaddy \
                  --dns-godaddy-propagation-seconds 120 \
                  --dns-godaddy-credentials c.ini \
                  --keep-until-expiring --non-interactive --expand \
                  --server https://acme-v02.api.letsencrypt.org/directory \
                  --agree-tos --email ${{ secrets.EMAIL }} \
                  -d ci2test.exptests.com
              cp -R /etc/letsencrypt/live/ /build
              ls /build
    - name: Copy out file from volume
      run: |
       sudo ls ${{ github.workspace }}/build
       sudo mkdir -p ${{ github.workspace }}/artifact
       sudo zip -r artifact.zip ${{ github.workspace }}/build
       sudo cp artifact.zip ${{ github.workspace }}/artifact
       sudo ls ${{ github.workspace }}/artifact

    - name: Upload certificate
      uses: actions/upload-artifact@v2
      with:
        name: certificate
        path: ${{ github.workspace }}/artifact
