name: Generate SSL Certificate

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  obtain-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Obtain SSL certificate
      uses: certbot/certbot@2.2.0
      with:
        args: certonly --webroot -w /github/workspace/public -d internal.exptests.com

    - name: Upload certificate
      uses: actions/upload-artifact@v2
      with:
        name: certificate
        path: /etc/letsencrypt/live/internal.exptests.com/
